### PR TITLE
[AEROGEAR-2636] Change bind parameters to compy to standard bind params schema

### PR DESCRIPTION
**Pull request by JameelB**
## Description
The bind parameters for client id and type needs to be consistent across all APBs. We need to change the bind parameters in the `apb.yml` to comply with this standard bind params schema.

## Progress
- [x] Change the bind params to comply with the standard bind params schema for client id and type.

## Screenshots
image

## Verification Steps

- Successfully provisioned UPS from this branch
- Secret and service binding created as expected after binding
- Secret and service binding cleaned up successfully after unbind

## Additional Notes
Related JIRA Ticket - https://issues.jboss.org/browse/AEROGEAR-2636

### CODE REVIEW

**Review by sedroche — APPROVED** [review]

**Review by dimitraz — APPROVED** [review]
:+1:

**Review by maleck13 — APPROVED** [review]

**Comment by dimitraz** [comment]
Verifying

**Review by dimitraz — CHANGES_REQUESTED** [review]
It looks like the `ups-config-operator` expects the key to be  `appType`, so this breaks the creation of the variant inside the ups console. I haven't finished testing if changing it to `clientType` works on that end yet because I'm haven't been able to build the docker image

**Review by dimitraz — APPROVED** [review]
Verified locally:

- [x] Successfully provisioned UPS from this branch
- [x] Secret and service binding created as expected after binding
- [x] Variant successfully created in the UPS console
- [x] Service shows up in client config component as expected 
- [x] Secret, service binding and UPS variant cleaned up successfully after unbind
- [x] Service is removed from client config component as expected

**Pull request merged**
