### PR TITLE
 fix: add bind parameter to specify production iOS cert

### PR DESCRIPTION
**Pull request by darahayes**
Adds the following to the wizard for binding:

screen shot 2018-05-01 at 15 58 00

@pb82 @cfoskin For some reason I do not see our own secret after the bind. I am seeing this behaviour in the master image too. It's strange because the apb does not fail and the apb logs appear as if everything happened properly. Have you guys experienced this?

### CODE REVIEW

**Comment by cfoskin** [comment]
@darahayes What do you mean our own secret? I ran a binding on this branch there for iOS and it worked fine and created the variant and the secret also with the config.

**Review by pb82 — APPROVED** [review]
LGTM, build failed due to timeout. If you don't see the secret after bind then it means it was successful: the sidecar service will delete the secret after it was used to create the variant. There should however be another secret with a name like `ups-secret-<clientId>-<random>` which is used to store all variant config for one client.

**Comment by darahayes** [comment]
Thanks for the clarification @pb82 didn't realise it was being deleted purposefully. I thought I was going crazy!

@cfoskin just to clear things up, as you know the `asb_encode_binding` thing in the playbook will result in a secret being created. This is this pretty standard but in addition to this we are creating our own secret [here](https://github.com/aerogearcatalog/unifiedpush-apb/blob/96cdbfe39f43eb715ca1522f130f859a8cf934e2/roles/bind-unifiedpush-apb/tasks/main.yml#L17-L18). The secret definition is [here](https://github.com/aerogearcatalog/unifiedpush-apb/blob/96cdbfe39f43eb715ca1522f130f859a8cf934e2/roles/bind-unifiedpush-apb/templates/binding_secret_ios.yml.j2). 

If my understanding is correct, the reason we do this is because we need some labels on the secret (not possible with the default `asb_encode_binding` one) so the sidecar service can search for it and pick it up.

As @pb82 mentioned, this secret gets removed by the sidecar service once it sees it and creates the appropriate resources in UPS. I was confused about why I wasn't seeing the secret after the provision because I didn't realise it gets deleted 😄

**Comment by cfoskin** [comment]
@darahayes  Yes I was not sure what secret you were talking about.

**Review by pb82 — APPROVED** [review]
Verified locally with https://github.com/aerogear/ups-config-operator/pull/31#pullrequestreview-116989313

**Pull request merged**
