### PR TITLE
Official No auth image update

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by pb82** [comment]
👀

**Comment by pb82** [comment]
@matzew i'm getting this error: `Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'installation' already exists`

**Comment by matzew** [comment]
@pb82 now this should be fine

**Review by pb82 — APPROVED** [review]
Verified locally

**Pull request merged**
